version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.26
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "5775:5775/udp" # zipkin.thrift over compact protocol (deprecated)
      - "6831:6831/udp" # jaeger.thrift over compact protocol
      - "6832:6832/udp" # jaeger.thrift over binary protocol
      - "5778:5778" # serve configs
      - "16686:16686" # serve frontend
      - "14268:14268" # accept jaeger.thrift directly from clients
      - "14250:14250" # accept model.proto
      - "9411:9411" # zipkin compatible endpoint
  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: newsletter
  subscriptions:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust-zero2prod
    restart: always
    environment:
      APP_EMAIL_CLIENT__API_KEY: ${EMAIL_CLIENT_API_KEY}
      APP_DATABASE__USERNAME: ${DATABASE_USER}
      APP_DATABASE__PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - jaeger