application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database_name: "newsletter"
  require_ssl: false
  connection_timeout: 2
tracing:
  service_name: "rust-zero2prod"
  log_level: "info"
  host: "localhost"
  port: 6831
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "marcel.schally@gmail.com"
  api_key: ""
  timeout_millis: 10000
template_engine:
  templates_dir: templates