application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
tracing:
  service_name: "rust-zero2prod"
  log_level: "info"
  host: "localhost"
  port: 6831
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "marcel.schally@gmail.com"
  authorization_token: "my-secret-token"
  timeout_millis: 10000